#---------------------------------#
#      general configuration      #
#---------------------------------#
 
# version format
version: 0.0.0.{build}                 # You can use {branch} to, for example
 
 
#---------------------------------#
#    environment configuration    #
#---------------------------------#
 
# Operating system (build VM template)
os: Windows Server 2012
 
# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
 
# fetch repository as zip archive
shallow_clone: true                 # default is "false"
 
 
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
 
 
#---------------------------------#
#       build configuration       #
#---------------------------------#
 
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU
  
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
  
build:
  parallel: true                  # enable MSBuild parallel builds
  project: src/StatDNS.sln        # path to Visual Studio solution or project
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: true             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
 
  # MSBuild verbosity level
  verbosity: quiet|minimal|normal|detailed
 
 
# scripts to run before build
before_build:
 
# scripts to run after build
after_build:
 
# to run your custom scripts instead of automatic MSBuild
build_script:
 
# to disable automatic builds
#build: off
 
#---------------------------------#
#       tests configuration       #
#---------------------------------#
 
test:
  assemblies:
    - StatDNS.Tests.dll
 
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
 
artifacts:
  - path: src\StatDNS\bin\$(configuration)
    name: StatDNS
 
  - path: out\*.nupkg
 
#---------------------------------#
#     deployment configuration    #
#---------------------------------#
 
 
# scripts to run before deployment
before_deploy:
 
# scripts to run after deployment
after_deploy:
 
# to run your custom scripts instead of provider deployments
deploy_script:
 
# to disable deployment
#deploy: off
 